name: Update GPTScript Version
on:
  repository_dispatch:
    types: release

jobs:
  update-gptscript-dep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install jq
        uses: dcarbone/install-jq-action@v2.1.0
      - name: Update GPTScript Version
        run: |
          jq '.version = "${{ github.event.client_payload.tag }}"' package.json > temp.json && mv temp.json package.json
          sed -i 's/version: "v[0-9.]*"/version: "${{ github.event.client_payload.tag }}"/' scripts/install-binary.js
      - uses: actions/setup-node@v4
        with:
          node-version: 21
      - name: Update Lock
        run: npm i --package-lock-only
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Automated GPTScript Version Update
          file_pattern: 'package*.json src/install-binary.js'
  tag-release:
    needs: update-gptscript-dep
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ github.event.client_payload.tag }}
          tag_prefix: ""
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
